rango/urls.py
from django.urls import path
from rango import views

app_name = 'rango'

urlpatterns = [
    path('', views.cover, name='cover'),
    path('index/', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('category/<slug:category_name_slug>/', views.show_category, name='show_category'),
    path('add_category/', views.add_category, name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', views.add_page, name='add_page'),
    path('restricted/', views.restricted, name='restricted'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('search/', views.search, name='search'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.cover, name='cover'),
    path('rango/', include('rango.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
    path('socialaccounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    NAME_MAX_LENGTH = 128
    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name
        
class Page(models.Model):
    TITLE_MAX_LENGTH =128
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile


class CategoryForm(forms.ModelForm):

    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                            help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Page
        exclude = ('category',)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

rango/views.py
from django.shortcuts import render
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from django.shortcuts import redirect
from django.urls import reverse
from rango.forms import PageForm
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from datetime import datetime
from django.contrib.auth.models import User 
from rango.models import UserProfile
from django.views import View
from rango.bing_search import run_query

def cover(request):
    return render(request, 'rango/cover.html', )

def index(request):
    category_list = Category.objects.order_by('-likes')[:8]
    page_list = Page.objects.order_by('-views')[:10]

    context_dict = {}
    context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
    context_dict['categories'] = category_list
    context_dict['pages'] = page_list

    visitor_cookie_handler(request)

    return render(request, 'rango/index.html', context=context_dict)

def about(request):
    context_dict = {}
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    return render(request, 'rango/about.html', context=context_dict)


def show_category(request, category_name_slug):
    context_dict = {}

    try:
        category = Category.objects.get(slug=category_name_slug)

        pages = Page.objects.filter(category=category)

        context_dict['pages'] = pages

        context_dict['category'] = category

    except Category.DoesNotExist:

        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context=context_dict)


@login_required
def add_category(request):
    form = CategoryForm()

    if request.method == 'POST':
        form = CategoryForm(request.POST)

    if form.is_valid():
        form.save(commit=True)
        return redirect(reverse('rango:index'))
    else:
        print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except:
        category = None

    if category is None:
        return redirect('rango:index')

    form = PageForm()
    
    if request.method == 'POST':
        form = PageForm(request.POST)
        
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return redirect(reverse('rango:show_category',
                                        kwargs={'category_name_slug':
                                                    category_name_slug}))

        else:
            print(form.errors)
    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)

@login_required
def restricted(request):
    return render(request, 'rango/restricted.html')

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,
                                               'last_visit',
                                               str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],
                                        '%Y-%m-%d %H:%M:%S')
    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] = last_visit_cookie

    request.session['visits'] = visits

class ProfileView(View):
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None

        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        form = UserProfileForm({'website': user_profile.website,
                                'picture': user_profile.picture})
        return (user, user_profile, form)

    
    def get(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))

        context_dict = {'user_profile': user_profile,
                         'selected_user': user,
                         'form': form}
        return render(request, 'rango/profile.html', context_dict)

    
    def post(self, request, username):
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))
        
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)
        
        context_dict = {'user_profile': user_profile,
                        'selected_user': user,
                        'form': form}

        return render(request, 'rango/profile.html', context_dict)


def search(request): 
    result_list = []
    if request.method == 'POST':
        query = request.POST['query'].strip() 
        if query:
            result_list = run_query(query)
            
    return render(request, 'rango/search.html', {'result_list': result_list})

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    About
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4" style="background-color:#222222">
    <div class="container" >
        <h1 class="jumbotron-heading" style="color:whitesmoke">About Our Team</h1>
    </div>
</div>
<div style="font-size: x-large">
    This tutorial has been put together by We need python :)<br />
</div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Category
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4" style="background-color:#222222">
    <div class="container">
        <h1 class="jumbotron-heading" style="color:whitesmoke">Add a Category</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="category_form" method="post" action="{% url 'rango:add_category' %}" style="font-size: x-large">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">Create Category</button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Page
{% endblock %}

{% block body_block %}
<div class="jumbotron p-4" style="background-color:#222222">
    <div class="container">
        <h1 class="jumbotron-heading" style="color:whitesmoke">Add a Page to {{ category.name }}</h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <form role="form" id="page_form" method="post" action="{% url 'rango:add_page' category.slug %}" style="font-size: x-large">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}<br />
                {{ field }}<br />
                <div class="p-2"></div>
            {% endfor %}
            <br />
            <button class="btn btn-primary" type="submit" name="submit">Add Page</button>
            <div class="p-5"></div>
        </form>
    </div>
</div>
{% endblock %}

templates/rango/base.html
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">


     <title>
         {% block title_block %}
         
         {% endblock %}
    </title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/dashboard.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

  {% block script_block %}
    {% endblock %}
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand p-2" href="{% url 'rango:cover' %}">Solocode</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'rango:search' %}">Search</a></li>
             {% if user.is_authenticated %}
             <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
             <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>          
             <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
             {% else %}
             <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
             <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
             {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">  
            {% block sidebar_block %}
                 {% get_category_list category %}
            {% endblock %}
          </ul>
          
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">

{% block body_block %}

{% endblock %}
          
          </div>

          
        </div>
      </div>
    </div>


    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'javascript/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'javascript/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/rango/categories.html
<ul class="nav flex-column">
{% if categories %}
    {% for c in categories %}
        {% if c == current_category %}
        <li class="nav-item">
            <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}">
                <span data-feather="archive"></span>{{ c.name }}
            </a>
        </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'rango:show_category' c.slug %}">
                <span data-feather="archive"></span>{{ c.name }}
            </a>
        </li>
        {% endif %}
    {% endfor %}
{% else %}
    <li class="nav-item">There are no categories present.</li>
{% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
    <div class="jumbotron p-4" style="background-color:#222222">
        <div class="container">
            <h1 class="jumbotron-heading" style="color:whitesmoke">{{ category.name }}</h1>
        </div>
    </div>
    {% if pages %}
    <ul>
        {% for page in pages %}
        <li style="font-size: xx-large"><a href="{{ page.url }}">{{ page.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No pages currently in category.</strong>
    {% endif %}

    {% if user.is_authenticated %}
    <a href="{% url 'rango:add_page' category.slug %}" style="font-size: xx-large">Add Page</a> <br />
    {% endif %}
    {% else %}
    The specified category does not exist.
    {% endif %}
{% endblock %}

templates/rango/cover.html
{% extends 'rango/newbase.html' %}
{% load staticfiles %}	

{% block title_block %}
    Solocode
{% endblock %}

	{% block body_block %}
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <img class="first-slide" src="{% static 'images/slide1.jpg' %}">
          <div class="container">
            <div class="carousel-caption">
              <h1 style="font-size:65px; height: 120px" >WHAT DO WE HAVE</h1>
              <p style="font-size:25px; height: 90px">A variety of programming courses and conservatively praised website recommendations</p>
              <p><a class="btn btn-lg btn-primary" href="{% url 'rango:index' %}" role="button">Learn now !</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img class="second-slide" src="{% static 'images/slide2.jpg' %}">
          <div class="container">
            <div class="carousel-caption">

              <h1 style="font-size:65px; height: 130px">EXPLORE A NEW WORLD</h1>
              <p style="font-size:25px; height: 80px">Search for more information</p>
              <p><a class="btn btn-lg btn-primary" href="{% url 'rango:search' %}" role="button">Search</a></p>

            </div>
          </div>
        </div>
        <div class="item">
          <img class="third-slide" src="{% static 'images/slide3.jpg' %}">
          <div class="container">
            <div class="carousel-caption">
              <h1 style="font-size:65px; height: 120px">JOIN US NOW</h1>
              <p style="font-size:25px; height: 90px">Click on the button to be one of us</p>
              <p><a class="btn btn-lg btn-primary" href="{% url 'registration_register' %}" role="button">Sign up today</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->



    <div class="container marketing">


      <div class="row">
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'images/c.jpg' %}" width="140" height="140">
          <h2>Dennis Ritchie</h2>
          <p>Dennis MacAlistair Ritchie (September 9, 1941 - October 12, 2011) was an American computer scientist. He created the C programming language and, with long-time colleague Ken Thompson, the Unix operating system and B programming language.</p>
          <p><a class="btn btn-default" href="https://en.wikipedia.org/wiki/Dennis_Ritchie" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'images/python.jpg' %}" width="140" height="140">
          <h2>Guido van Rossum</h2>
          <p>Guido van Rossum (born 31 January 1956) is a Dutch programmer best known as the creator of the Python programming language, for which he was the "benevolent dictator for life" (BDFL) until he stepped down from the position in July 2018.</p>
          <p><a class="btn btn-default" href="https://en.wikipedia.org/wiki/Guido_van_Rossum" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="{% static 'images/java.jpg' %}" width="140" height="140">
          <h2>James Arthur Gosling</h2>
          <p>James Arthur Gosling, often referred to as "Dr. Java", OC (born May 19, 1955) is a Canadian computer scientist, best known as the founder and lead designer behind the Java programming language.</p>
          <p><a class="btn btn-default" href="https://en.wikipedia.org/wiki/James_Gosling" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->




      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">C programming language</h2>
          <p class="lead">C is an imperative procedural language. It was designed to be compiled to provide low-level access to memory and language constructs that map efficiently to machine instructions, all with minimal runtime support. Despite its low-level capabilities, the language was designed to encourage cross-platform programming. A standards-compliant C program written with portability in mind can be compiled for a wide variety of computer platforms and operating systems with few changes to its source code.</p>
          <p><a class="btn btn-default" href="category/c-programming/" role="button">Learn C &raquo;</a></p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" src="{% static 'images/image1.jpg' %}">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Python</h2>
          <p class="lead">Python is an interpreted high-level general-purpose programming language. Python's design philosophy emphasizes code readability with its notable use of significant indentation. Its language constructs as well as its object-oriented approach aim to help programmers write clear, logical code for small and large-scale projects.</p>
          <p><a class="btn btn-default" href="category/python/" role="button">Learn Python &raquo;</a></p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" src="{% static 'images/image2.jpg' %}">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Java</h2>
          <p class="lead">Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible. It is a general-purpose programming language intended to let application developers write once, run anywhere, meaning that compiled Java code can run on all platforms that support Java without the need for recompilation.</p>
          <p><a class="btn btn-default" href="category/java/" role="button">Learn Java &raquo;</a></p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" src="{% static 'images/image3.jpg' %}">
        </div>
      </div>

      <hr class="featurette-divider">

 <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2021 We need Python</p>
</footer>


</div>
{% endblock %}
</html>

templates/rango/newbase.html
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

     <title>
         {% block title_block %}
         
         {% endblock %}
    </title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="navbar-wrapper">
      <div class="container">

        <nav class="navbar navbar-inverse navbar-static-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand p-2" href="{% url 'rango:cover' %}">Solocode</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
          <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
          <li class="nav-item "><a class="nav-link" href="{% url 'rango:search' %}">Search</a></li>
             {% if user.is_authenticated %}
             <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
             <li class="nav-item"><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
             <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
             {% else %}
             <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
             <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
             {% endif %}
          </ul>
        </div>
      </div>
    </nav>

      </div>
    </div>

{% block body_block %}

{% endblock %}
    <script src="https://code.jquery.com/jquery-1.12.4.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="{% static 'javascript/jquery.min.js' %}"><\/script>')</script>
    <script src="{% static 'javascript/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/rango/profile.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Profile for {{ selected_user.username }}
{% endblock %}

{% block body_block %} 
<div class="jumbotron p-4" style="background-color:#222222">
    <div class="container"></div>
        <h1 class="jumbotron-heading" style="color:whitesmoke">{{ selected_user.username }}'s Profile</h1>
    </div>

    </div>
</div>
<div class="container" style="position:relative;left:150px;font-size: x-large">
    <div class="row" >
        <img src="{{ MEDIA_URL }}{{ user_profile.picture }}"
        width="300"
        height="300"
        alt="{{ selected_user.username }}'s profile image" />
        <br />
    </div>
    {% if selected_user == user %}
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <input type="submit" value="Update" />
       
            <p style="margin: 30px"><a class="btn btn-lg btn-primary" href="{% url 'auth_password_change' %}" role="button">Change Password</a></p>
        
        
    </form>
    {% else %}
    <p>
    </p>
    {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/rango/search.html
{% extends 'rango/base.html' %}
{%load staticfiles%}

{% block title_block %}
     Search
{%endblock%}

{% block body_block %}
<div class="jumbotron p-4" style="background-color:#222222;">
    <div class="container">
        <h1 class="jumbotron-heading" style="color:whitesmoke">Search</h1>
    </div>
</div>
<div>
    <form class="form-inline"
    id="user-form"
      method="post"
      action="{% url 'rango:search' %}">
    {% csrf_token %}

    <div class="form-group">
        <input class="form-control"
        type="text"
        size="50"
        name="query"
        id="query" />
    </div>

    <button class="btn btn-primary"
            type="submit"
            name="submit">Search</button>
    </form>
</div>
<div>
    {% if result_list %}
    <h2 style=" top: 5px">Results</h2>

    <div class="list-group">
        {% for result in result_list %}
           <div class="list-group-item">
              <h3 class="list-group-item-heading">
                  <a href="{{ result.link }}">
                      {{ result.title|safe|escape }}
                    </a>
                </h3>
                <p class="list-group-item-text">
                    {{ result.summary|safe|escape }}
                </p>
            </div>
            {% endfor %}
        </div>
    {% endif %}
</div>
{%endblock%}